# 自定义异常
在 Java 中，我们可以通过继承 `Exception` 或 `RuntimeException` 类来定义自己的异常类。

继承 `Exception` 类的自定义异常类通常用于表示程序运行时的一般性异常情况，需要在方法声明中使用 `throws` 关键字进行声明或使用 `try-catch` 语句进行处理。

继承 `RuntimeException` 类的自定义异常类通常用于表示程序中的逻辑错误，不需要在方法声明中使用 `throws` 关键字进行声明，也可以在需要时使用 `try-catch` 语句进行处理。

下面是一个继承 `Exception` 类的自定义异常类的示例代码：

```java
public class MyException extends Exception {
    public MyException(String message) {
        super(message);
    }
}
```

在这个示例代码中，我们通过继承 `Exception` 类来定义自己的异常类 `MyException`，并重写了其构造方法，以便传递异常信息。

下面是一个使用自定义异常类的示例代码：

```java
public class MyClass {
    public void myMethod(int x) throws MyException {
        if (x < 0) {
            throw new MyException("x cannot be negative");
        }
        // other code here
    }
}
```

在这个示例代码中，我们在 `myMethod()` 方法中检查参数 `x` 是否小于 0，如果小于 0，则抛出自定义异常类 `MyException` 的实例，并传递异常信息。

在调用 `myMethod()` 方法时，我们需要使用 `throws` 关键字进行声明或使用 `try-catch` 语句进行处理，以便正确处理自定义异常。